### PR TITLE
Add encryption of user data to checkin

### PR DESCRIPTION
**Pull request by timomeh**
Using the crypto demo from @MaxKellermann in #2, I added the encryption of userdata and the api communication to the checkin.

@MaxKellermann Do you want to take a loot at it? The encryption happens inside `createCheckin` in lib/api.ts

### CODE REVIEW

**Comment by timomeh** [comment]
@MaxKellermann Feel free to look at it to check if I'm am doing anything wrong, if you'd like. I'm going to merge this so we can continue.

**Comment by MaxKellermann** [comment]
I'm not a JS/Node guy ... but does this encryption run on the client (browser) or on the server (node)?

**Comment by MaxKellermann** [comment]
I'm confident enough that this runs server-side.
To me, it makes no sense to copy the data in cleartext from the client to the server, and let the server encrypt it. The server should never see any personal data in the first place - a server breach should never expose any data. The client should encrypt, and send the encrypted file to the server.

**Comment by timomeh** [comment]
The encryption runs entirely client side. Nothing in here happens server-side :) our server is in railslove/rcvr-api

The user data is stored in the Browser's IndexedDB on the client.

**Comment by MaxKellermann** [comment]
Uh, so this whole obscure Node stuff (Node being a server-side thing) is just there to make the client stuff available, and there is no "real" server-side code at all in this repository - that's why I was confused... I couldn't imagine you would split one application into two repositories.

**Pull request merged**
