### PR TITLE
💬 Update texts for health env and add some design changes

### PR DESCRIPTION
**Pull request by P3nny**

### CODE REVIEW

**Comment by salimhb** [comment]
Why is the `<Warning />` Icon only added for care and health and not the rcvr whitelabel?
Some Screenshots showing the design changes would be nice to see in the description.

**Comment by P3nny** [comment]
Bildschirmfoto vom 2020-11-24 15-01-42
Bildschirmfoto vom 2020-11-24 15-01-13
Bildschirmfoto vom 2020-11-24 15-00-47
Bildschirmfoto vom 2020-11-24 15-00-05

@salimhb Here are the screenshots of the design changes in onboarding.
The commit contains further text and link improvements I discussed with Max this morning.

**Review by salimhb — APPROVED** [review]

**Review by timomeh — APPROVED** [review]
Looks good! 👌 

Not related to this specific PR, but: I would advise to replace all the conditionals for different texts with i18n soon (treating a whitelabel as its own language). My concern is that more whitelabels/text-variants will cause more 🍝-code. Then we could also add support for different languages, e.g. english.

**Pull request merged**
