### PR TITLE
Fix wrongly decoded URL in Safari

### PR DESCRIPTION
**Pull request by timomeh**
We received bugreports from some people that they can't checkin.
After closer examination, there are two problems coming together:

   - some QR Code Scanners encode the URL params before redirecting to
     the browser
   - iOS Safari decodes already decoded params wrong with
     URLSearchParams

This means we can't use URLSearchParams to parse the url params. Thus
I replaced it with a regex. Yes, a regex. It's not optimal because it
requires that the order of the params is fixed (?a=...&k=...), but
it fixes the problem.

### CODE REVIEW

**Comment by timomeh** [comment]
This is not our final solution. It's not ready to merge. Maybe we just show an error message and inform the user that their QR Code Scanner is the problem.

**Comment by mfranzke** [comment]
@timomeh, does the same problem occur with location.search ?
https://www.w3schools.com/jsref/prop_loc_search.asp

**Comment by mfranzke** [comment]
@timomeh, does the problem occur on hash values as well? As those get preserved on redirects and the values would need to get retrieved on the client side via JS (at least to my understanding) this might be an alternative solution.

**Comment by mfranzke** [comment]
@timomeh, if you’re as well looking for a solution regarding differentiation/detection whether the params have been decoded, what about adding an additional fixed param at the end of the URL that you easily parse and check for either encoded or decoded, like e.g.:
&test

If those last 8 chars at the end are „%26test“ instead, it‘s encoded and elsewhere it‘s not.

**Comment by timomeh** [comment]
> does the same problem (on iOS) occur with location.search ?

No, `location.search` works fine – that's why I used it in this PR and parsed it with a regex 🙂 It only seems to be a problem with [`URLSearchParams`](https://developer.mozilla.org/de/docs/Web/API/URLSearchParams).

...but I don't really want to parse `location.search`. 😅 It works, but parsing it with a regex sounds like it could cause another weird issue we didn't think of.

I'd rather catch the error and show a nice error screen, explaining that the users QR Code scanner doesn't work well and linking to our /qr route.

> And for a differentiation/detection whether the params have been decoded, what about adding an additional fixed param at the end of the URL that you easily parse and check for either encoded or decoded, like e.g.:
&test

That's a good idea! The param needs to be added to the QR Code though, and there are already a lot of QR Codes printed. But nonetheless it's a good idea and I'll discuss this with the team. We could use this to really make sure the error comes from the wrongly encoded search param, and not from something else in the encryption phase.

> does the problem occur on hash values as well?

I don't know, and that's not something I want to do, to be honest. Query Params are the way to go.

---

I'm currently working on a big cleanup of the app. It evolved quite fast with many requirements changing in a quickly manner, without any time for refactoring. I'll add a better error handling for this issue as well during the cleanup.

**Comment by timomeh** [comment]
I did a big cleanup of the codebase and added a nice error message for this behavior while I was at it. This PR is now obsolete. 🚀

**Pull request closed without merging**
